### ISSUE TITLE
Can't install beta through BRAT

### ISSUE THREAD

**Issue by joshtownley** [TomNCatz/obsidian-gallery#13]
When I try to install via BRAT, I get the error "the release is not complete and cannot be downloaded. main.js is missing from the Release"
Similarly, when I try to manually download the zip and add it to the plugins folder, I see the plugin in the Community Plugins list, but I cannot enable it.
This is probably down to my own ignorance rather than an actual issue/bug.

**Comment by TomNCatz** [comment]
That's interesting. I've never actually used BRAT, so I'll have to load it up and see what it wants. Perhaps because I've been making all the releases as ACTUAL releases instead of preview releases it doesn't know what to do with that? I would think it would take the latest release regardless of if it is a preview or not, but my releases all seem to have the correct files in them. I'll try looking into this over my lunch break.

**Comment by TomNCatz** [comment]
Got this working eventually. Seems that both Obsidian and BRATs use file in the repo instead of the releases to figure out what to load, so I'll have to be careful what commits I make between releases
