### ISSUE TITLE
Ability to search and filter by other property fields

### ISSUE THREAD

**Issue by TonyAtlas** [TomNCatz/obsidian-gallery#19]
Is it possible to make it so that for example instead of tags it would be possible to create its own field and make a search on this field?

I do not want to mix tags for pictures and tags for the rest of the database as entities. Therefore I would like to create a separate property for picture tags.

Thank you. You've made a very cool tool that I've been missing in Obsidian.

**Comment by TomNCatz** [comment]
the very last update makes this possible!
if you have a property in your frontmatter for the meta file with a list of text items, those are can be used in the advanced search by specifying the name of the property a colon, and then your search criteria as if it were tags eg. imgTag:photo -art

Any properties you've added to the meta will also get shown in the info to the right unless hidden in settings or the file(which by default I only hide some fields I've added)

Now, all that said, it's not super easy to edit that field in the sidebar like the main tags field is. You currently have to click the edit button at the top and manually edit it without the support of autocomplete. Part of this is that I lean a little on obsidian's tag support, but also I just don't know what meta fields you'll want. Also, any images you import that already have tags will put those tags in the tag field. I guess I could write add a setting that like, re-targets most of that at a different field, but you'd still lose out on obsidian's built in tag support.

If the frontmatter filtering doesn't meet your needs then I can look into some sort of retargetting setting, but otherwise I'll close this ticket.

**Comment by TonyAtlas** [comment]
I would really like to be able to auto-complete the text for the properties I created.

I would like to have a property for images that would be analogous to tags and filled in the same way with auto-completion as tags, because I plan a large number of different values and of course it will be difficult to enter them manually, because I just won't remember them all.

In my case, I don't plan to use the standard tag property for pictures at all, because they are used for the notes themselves.

If it is possible to implement such a request, then I would be very grateful.
