### ISSUE TITLE
 Оbsidian plugin gallery

### ISSUE THREAD

**Issue by lilianzzz** [TomNCatz/obsidian-gallery#39]
Maybe it's time to add  to the Оbsidian plugin gallery?

**Comment by TomNCatz** [comment]
Apologies, I wish I could. Since this is actually a fork of Darakah's plugin, they added it to the official list, but didn't add a license to it, and they are no longer around to comment, my submission was refused. My understanding is this was due to legal liability on the part of Obsidian.

I reached out, but if Darakah does not come back and make some form of change then I am unable to make it official.
