### ISSUE TITLE
plz add .gif support

### ISSUE THREAD

**Issue by incantatem1** [TomNCatz/obsidian-gallery#41]
i did it myself by just adding .gif to the list of file extensions, but i don't understand javascript and it's scary. i have a lot of gifs and want them to be in the gallery.

**Comment by TomNCatz** [comment]
oh, my bad, I thought it was already in the list, I'll get that in

**Comment by TomNCatz** [comment]
Uh, actually, this seems to be working for me. are you sure that you are currently using the most up to date version of my fork and not an old version or the version by Darakah?
![image](https://github.com/user-attachments/assets/5ca301be-f806-4057-baef-5e8b16a29de3)

**Comment by incantatem1** [comment]
I was using the old version (and still am, I just added the gif support myself). I don't know how to download the newest version.

**Comment by TomNCatz** [comment]
I use the BRAT community plugin to manage stuff like this personally, and that would be my advice. I'd love for this to be a community plugin so that it was easier, And I may discuss it with them again now that the original developer has closed their account and repo.

All that said, depending on how old of a version you are coming from there is a chance there are breaking changes in the config and metadata files. I have tried to keep those to a minimum, but there were a few a ways back in developement
