### ISSUE TITLE
[Bug] The image management interface always refreshes unexpectedly

### ISSUE THREAD

**Issue by wwjCMP** [TomNCatz/obsidian-gallery#5]
The image management interface always refreshes unexpectedly, which greatly affects the reading experience. I really hope you can find a way to reduce its unnecessary refreshes.Thank you.

**Comment by TomNCatz** [comment]
refreshes? As in images that have already loaded show their loading spinner again?
Is the on mobile or desktop? 
When does it happen? When you are resizing an element? When you are scrolling? When you change a field or click somewhere?

I see an issue on mobile where when you add tags on the right hand side it is resizing the window slightly and that is causing a resize event, I'm planning to require the size to change by a certain amount before triggering a resize to solve for this. If your reproduction steps line up with that I may have a fix coming but otherwise I'll have to figure out how to reproduce your issue.
